url: "" # the base hostname & protocol for your site, e.g. http://example.com
source: _jekyll
destination: _site
# baseurl: /blog
title: "" # the name of your site, e.g. ACME Corp.
# index_file: index.html
plugins:
  - jekyll-postcss
  - jekyll-timeago
  - jekyll-paginate-v2

# permalink: /blog/:year/:month/:day/:title/

postcss:
  cache: false

jekyll_timeago:
  depth: 2
  default_locale: "en"
  fallbacks: true

pagination:
  enabled: true
  per_page: 9
  permalink: "/page/:num/"
  title: ":title - page :num"
  sort_field: "date"
  sort_reverse: true
